### ISSUE TITLE
Client doesn't allow for player to be in jail

### ISSUE THREAD

**Issue by adamgillessen** [adamgillessen/monopoly#17]
When a client is in jail, they shouldn't be able to move from jail unless they roll a double or they pay the $50 bail.

If a player is in jail {
---If they roll a double {
------- they can continue as normal with the double as their dice roll (they don't get a second turn)
---} else {
--------They must wait until their next turn to roll a double
--------// the next message the server expects in this case is an end_turn message
----}
}

The player can choose to pay their bail. To make this simpler, I will define a pay_bail message which can be sent outside of a player's turn. If they have chosen to pay bail, when it is their turn they roll the dice and continue their turn as normal.

**Comment by NooBJeff** [comment]
The player seem stay in Jail forever if they don't pay bail or don't roll a double.
I think player should be free after stay in Jail for 3 rounds?

**Comment by asvrada** [comment]
Jail function Added

**Comment by asvrada** [comment]
But Use Card still not added...

**Comment by asvrada** [comment]
Use card function added
