### ISSUE TITLE
Define more message to describe certain event

### ISSUE THREAD

**Issue by asvrada** [adamgillessen/monopoly#20]
Server to Client:
2. ~~When Player goes to jail~~
2. ~~When player gets Get Out of Jail Free card (Need to discuss this whole Jail-related game logic flow later)~~
3. ~~When player gets moved to a square because of Chance Card or Cumminty Chest Card~~

Client to Server:

More to be added, this is getting really messy because we code before designing the game flow.

**Comment by adamgillessen** [comment]
I already have the pay_bail, get out of...card implemented.

The get out of jail free card is already in the board_sync message in the players section

A textual update is now sent when a player pays rent to someone so they know before their turn is over.
