### ISSUE TITLE
Clients can join a game which is in progress

### ISSUE THREAD

**Issue by adamgillessen** [adamgillessen/monopoly#24]

**Comment by asvrada** [comment]
Client should be notified (by a new message) if the game it is joining is in progress, otherwise its impossible to know if this server is available or not on the client side with.

**Comment by adamgillessen** [comment]
I think this is a separate issue (we should discuss in the meeting). I think instead of connecting to a server and portnumber, their should just be a "Connect to a Game" button and an AJAX request will send a request to the server and get the port number of the current game which the websocket can then connect to.
